// Generated by CoffeeScript 1.3.3
(function() {
  var bg, draw, fg, init, owner, vars, write_colors;

  vars = new Array();

  owner = "";

  bg = function(selector, color) {
    return $(selector).css('background-color', color);
  };

  fg = function(selector, color) {
    return $(selector).css('color', color);
  };

  init = function() {
    var sel, _fn;
    _fn = function(sel) {
      bg('#' + sel, vars[sel]);
      $('#' + sel).text(vars[sel]);
    };
    for (sel in vars) {
      _fn(sel);
    }
    draw();
    $('#color_box').hide();
  };

  write_colors = function() {
    return $('#output').text('static const char normbordercolor[] = "' + vars['unsel_border'] + '";\n' + 'static const char normbgcolor[]     = "' + vars['unsel_bg'] + '";\n' + 'static const char normfgcolor[]     = "' + vars['unsel_fg'] + '";\n' + 'static const char selbordercolor[]  = "' + vars['sel_border'] + '";\n' + 'static const char selbgcolor[]      = "' + vars['sel_bg'] + '";\n' + 'static const char selfgcolor[]      = "' + vars['sel_fg'] + '";');
  };

  draw = function() {
    fg('.dwm_nav', vars['unsel_fg']);
    bg('.dwm_nav', vars['unsel_bg']);
    fg('.dwm_nav_sel', vars['sel_fg']);
    bg('.dwm_nav_sel', vars['sel_bg']);
    bg('.dwm_nav_bar', vars['unsel_bg']);
    bg('.dwm_wrap', vars['sel_bg']);
    fg('.dwm_bar', vars['sel_fg']);
    bg('.dwm_bar', vars['sel_bg']);
    fg('.dwm_title', vars['sel_fg']);
    bg('.dwm_title', vars['sel_bg']);
    fg('.dwm_root', vars['unsel_fg']);
    bg('.dwm_root', vars['unsel_bg']);
    $('#output').css('border', 'solid 5px ' + vars['unsel_border']);
    write_colors();
  };

  $(document).ready(function() {
    var cw, selected_item, selected_nav;
    selected_item = "";
    selected_nav = $('#nav_4');
    selected_nav.addClass('dwm_nav_sel');
    vars['sel_fg'] = '#000000';
    vars['sel_bg'] = '#1b7ee0';
    vars['unsel_fg'] = '#ffffff';
    vars['unsel_bg'] = '#393939';
    vars['sel_border'] = '#aaaaaa';
    vars['unsel_border'] = '#0d0d0d';
    init();
    cw = Raphael.colorwheel($('#color_box')[0], 300, 300);
    cw.color($('#sel_fg').css('background-color'));
    $('#output').hover(function() {
      return $(this).css('border', 'solid 5px ' + vars['sel_border']);
    }, function() {
      return $(this).css('border', 'solid 5px ' + vars['unsel_border']);
    });
    $('.dwm_edit_box').click(function() {
      $('#color_box').show();
      if (owner) {
        owner.css('border-left', 'solid 0px #ffffff');
      }
      owner = $(this);
      owner.css('border-left', 'solid 5px #ffffff');
      selected_item = this.id;
      cw.color($(this).css('background-color'));
      cw.onchange(function(color) {
        owner.css('background-color', cw.color().hex);
        owner[0].textContent = cw.color().hex;
        vars[selected_item] = cw.color().hex;
        draw();
      });
    });
    $('.dwm_nav').click(function() {
      selected_nav.removeClass('dwm_nav_sel');
      selected_nav = $(this);
      selected_nav.addClass('dwm_nav_sel');
      return draw();
    });
  });

}).call(this);
